import type { Quote, Language } from '$lib/types';

export async function generateQuotePdf(quote: Quote, language: Language): Promise<void> {
	// Dynamic import to avoid SSR issues
	const { pdf, Document, Page, Text, View, StyleSheet, Image } = await import('@react-pdf/renderer');
	const React = await import('react');

	const t = {
		es: {
			title: 'Cotizacion de Aire Acondicionado',
			date: 'Fecha',
			spaceAnalysis: 'Analisis del Espacio',
			thermalCalc: 'Calculo Termico',
			options: 'Opciones Recomendadas',
			dimensions: 'Dimensiones',
			windows: 'Ventanas',
			roomType: 'Tipo de espacio',
			occupants: 'Ocupantes',
			totalRequired: 'Total requerido',
			equivalent: 'Equivalente a',
			capacity: 'Capacidad',
			efficiency: 'Eficiencia',
			priceRange: 'Rango de precio',
			monthlyCost: 'Costo mensual aprox.',
			economic: 'Economica',
			recommended: 'Recomendada',
			premium: 'Premium',
			disclaimer: 'Esta cotizacion es referencial y tiene validez de 30 dias. Los precios finales pueden variar segun disponibilidad y evaluacion tecnica presencial.',
			footer: 'Generado con IA por Trybotix Labs',
			ctaTitle: 'Esto fue un demo de Trybotix Labs',
			ctaSubtitle: 'La misma logica puede aplicarse a tu negocio: cotizaciones automaticas, analisis de documentos, diagnosticos por fotos.',
			ctaQuestion: 'Tienes un proceso que podria funcionar asi?',
			ctaButton: 'www.trybotix.com',
			ctaEmail: 'christian.ramirez@trybotix.com'
		},
		en: {
			title: 'Air Conditioning Quote',
			date: 'Date',
			spaceAnalysis: 'Space Analysis',
			thermalCalc: 'Thermal Calculation',
			options: 'Recommended Options',
			dimensions: 'Dimensions',
			windows: 'Windows',
			roomType: 'Space type',
			occupants: 'Occupants',
			totalRequired: 'Total required',
			equivalent: 'Equivalent to',
			capacity: 'Capacity',
			efficiency: 'Efficiency',
			priceRange: 'Price range',
			monthlyCost: 'Est. monthly cost',
			economic: 'Economic',
			recommended: 'Recommended',
			premium: 'Premium',
			disclaimer: 'This is a reference quote valid for 30 days. Final prices may vary based on availability and on-site technical evaluation.',
			footer: 'AI Generated by Trybotix Labs',
			ctaTitle: 'This was a demo by Trybotix Labs',
			ctaSubtitle: 'The same logic can apply to your business: automated quotes, document analysis, photo diagnostics.',
			ctaQuestion: 'Have a process that could work like this?',
			ctaButton: 'www.trybotix.com',
			ctaEmail: 'christian.ramirez@trybotix.com'
		}
	};

	const labels = t[language];

	// Create styles
	const styles = StyleSheet.create({
		page: {
			padding: 40,
			fontFamily: 'Helvetica',
			fontSize: 10,
			color: '#1f2937'
		},
		header: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			marginBottom: 30,
			paddingBottom: 20,
			borderBottomWidth: 2,
			borderBottomColor: '#2563eb'
		},
		logo: {
			flexDirection: 'row',
			alignItems: 'center'
		},
		logoImage: {
			height: 30,
			objectFit: 'contain'
		},
		logoText: {
			fontSize: 18,
			fontWeight: 'bold',
			color: '#2563eb'
		},
		logoSub: {
			fontSize: 8,
			color: '#6b7280'
		},
		ctaLogoImage: {
			height: 35,
			marginBottom: 10,
			objectFit: 'contain'
		},
		title: {
			fontSize: 20,
			fontWeight: 'bold',
			color: '#111827',
			marginBottom: 8
		},
		date: {
			fontSize: 10,
			color: '#6b7280'
		},
		section: {
			marginBottom: 20
		},
		sectionTitle: {
			fontSize: 12,
			fontWeight: 'bold',
			color: '#2563eb',
			marginBottom: 10,
			paddingBottom: 5,
			borderBottomWidth: 1,
			borderBottomColor: '#e5e7eb'
		},
		grid: {
			flexDirection: 'row',
			flexWrap: 'wrap'
		},
		gridItem: {
			width: '50%',
			marginBottom: 8
		},
		label: {
			fontSize: 8,
			color: '#6b7280',
			marginBottom: 2
		},
		value: {
			fontSize: 10,
			fontWeight: 'bold'
		},
		optionCard: {
			padding: 15,
			marginBottom: 10,
			backgroundColor: '#f9fafb',
			borderRadius: 8,
			borderWidth: 1,
			borderColor: '#e5e7eb'
		},
		optionRecommended: {
			borderColor: '#2563eb',
			borderWidth: 2,
			backgroundColor: '#eff6ff'
		},
		optionHeader: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			marginBottom: 10
		},
		optionTitle: {
			fontSize: 12,
			fontWeight: 'bold'
		},
		badge: {
			backgroundColor: '#2563eb',
			color: 'white',
			fontSize: 7,
			padding: '3 8',
			borderRadius: 4
		},
		optionSpecs: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			marginBottom: 8
		},
		optionSpec: {
			width: '50%',
			marginBottom: 4
		},
		optionPrice: {
			fontSize: 14,
			fontWeight: 'bold',
			color: '#111827'
		},
		totalBox: {
			backgroundColor: '#2563eb',
			padding: 15,
			borderRadius: 8,
			marginVertical: 15
		},
		totalText: {
			color: 'white',
			textAlign: 'center'
		},
		totalValue: {
			fontSize: 24,
			fontWeight: 'bold',
			color: 'white',
			textAlign: 'center'
		},
		disclaimer: {
			fontSize: 8,
			color: '#6b7280',
			marginTop: 20,
			padding: 10,
			backgroundColor: '#f9fafb',
			borderRadius: 4
		},
		footer: {
			position: 'absolute',
			bottom: 30,
			left: 40,
			right: 40,
			textAlign: 'center',
			fontSize: 8,
			color: '#9ca3af',
			borderTopWidth: 1,
			borderTopColor: '#e5e7eb',
			paddingTop: 10
		},
		ctaBox: {
			marginTop: 20,
			padding: 20,
			backgroundColor: '#f0fdfa',
			borderRadius: 8,
			borderWidth: 2,
			borderColor: '#22d3ee',
			alignItems: 'center'
		},
		ctaLogo: {
			width: 40,
			height: 40,
			marginBottom: 10
		},
		ctaBrand: {
			flexDirection: 'row',
			alignItems: 'center',
			marginBottom: 10
		},
		ctaBrandText: {
			fontSize: 14,
			fontWeight: 'bold',
			color: '#111827'
		},
		ctaBrandLabs: {
			fontSize: 10,
			color: '#22d3ee',
			marginLeft: 4
		},
		ctaTitle: {
			fontSize: 12,
			fontWeight: 'bold',
			color: '#111827',
			textAlign: 'center',
			marginBottom: 8
		},
		ctaSubtitle: {
			fontSize: 9,
			color: '#6b7280',
			textAlign: 'center',
			marginBottom: 8
		},
		ctaQuestion: {
			fontSize: 10,
			fontWeight: 'bold',
			color: '#2563eb',
			textAlign: 'center',
			marginBottom: 10
		},
		ctaButton: {
			backgroundColor: '#22d3ee',
			color: '#111827',
			fontSize: 10,
			fontWeight: 'bold',
			padding: '8 16',
			borderRadius: 6,
			textAlign: 'center'
		}
	});

	// Get logo URL (works in browser context)
	const logoUrl = typeof window !== 'undefined' ? `${window.location.origin}/trybotix-logo.png` : '/trybotix-logo.png';

	// Create document
	const QuoteDocument = () =>
		React.createElement(
			Document,
			null,
			React.createElement(
				Page,
				{ size: 'A4', style: styles.page },
				// Header
				React.createElement(
					View,
					{ style: styles.header },
					React.createElement(
						View,
						{ style: styles.logo },
						React.createElement(Image, { style: styles.logoImage, src: logoUrl })
					),
					React.createElement(
						View,
						null,
						React.createElement(Text, { style: styles.title }, labels.title),
						React.createElement(
							Text,
							{ style: styles.date },
							`${labels.date}: ${new Date().toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US')}`
						)
					)
				),
				// Space Analysis Section
				React.createElement(
					View,
					{ style: styles.section },
					React.createElement(Text, { style: styles.sectionTitle }, labels.spaceAnalysis),
					React.createElement(
						View,
						{ style: styles.grid },
						React.createElement(
							View,
							{ style: styles.gridItem },
							React.createElement(Text, { style: styles.label }, labels.dimensions),
							React.createElement(
								Text,
								{ style: styles.value },
								`${quote.analysis.dimensions.area.toFixed(1)} m² (${quote.analysis.dimensions.width.toFixed(1)} × ${quote.analysis.dimensions.length.toFixed(1)} m)`
							)
						),
						React.createElement(
							View,
							{ style: styles.gridItem },
							React.createElement(Text, { style: styles.label }, labels.windows),
							React.createElement(
								Text,
								{ style: styles.value },
								`${quote.analysis.windows.count} (${quote.analysis.windows.orientation})`
							)
						),
						React.createElement(
							View,
							{ style: styles.gridItem },
							React.createElement(Text, { style: styles.label }, labels.roomType),
							React.createElement(Text, { style: styles.value }, quote.analysis.roomType)
						),
						React.createElement(
							View,
							{ style: styles.gridItem },
							React.createElement(Text, { style: styles.label }, labels.occupants),
							React.createElement(Text, { style: styles.value }, String(quote.analysis.estimatedOccupancy))
						)
					)
				),
				// Total Box
				React.createElement(
					View,
					{ style: styles.totalBox },
					React.createElement(Text, { style: styles.totalText }, labels.totalRequired),
					React.createElement(
						Text,
						{ style: styles.totalValue },
						`${quote.calculation.totalBtu.toLocaleString()} BTU`
					),
					React.createElement(
						Text,
						{ style: styles.totalText },
						`${labels.equivalent} ${quote.calculation.tonnage.toFixed(1)} TR`
					)
				),
				// Options Section
				React.createElement(
					View,
					{ style: styles.section },
					React.createElement(Text, { style: styles.sectionTitle }, labels.options),
					...quote.options.map((option) =>
						React.createElement(
							View,
							{
								key: option.id,
								style: option.isRecommended
									? [styles.optionCard, styles.optionRecommended]
									: styles.optionCard
							},
							React.createElement(
								View,
								{ style: styles.optionHeader },
								React.createElement(
									Text,
									{ style: styles.optionTitle },
									labels[option.tier as keyof typeof labels] || option.tier
								),
								option.isRecommended &&
									React.createElement(Text, { style: styles.badge }, 'RECOMENDADA')
							),
							React.createElement(
								View,
								{ style: styles.optionSpecs },
								React.createElement(
									View,
									{ style: styles.optionSpec },
									React.createElement(Text, { style: styles.label }, labels.capacity),
									React.createElement(
										Text,
										{ style: styles.value },
										`${option.totalBtu.toLocaleString()} BTU`
									)
								),
								React.createElement(
									View,
									{ style: styles.optionSpec },
									React.createElement(Text, { style: styles.label }, labels.efficiency),
									React.createElement(
										Text,
										{ style: styles.value },
										`SEER ${option.units[0]?.seer || '-'}`
									)
								),
								React.createElement(
									View,
									{ style: styles.optionSpec },
									React.createElement(Text, { style: styles.label }, labels.monthlyCost),
									React.createElement(Text, { style: styles.value }, `$${option.estimatedMonthlyCost}`)
								)
							),
							React.createElement(
								Text,
								{ style: styles.optionPrice },
								`$${option.estimatedPrice.min.toLocaleString()} - $${option.estimatedPrice.max.toLocaleString()} USD`
							)
						)
					)
				),
				// CTA Box - Bridge to Trybotix
				React.createElement(
					View,
					{ style: styles.ctaBox },
					React.createElement(Image, { style: styles.ctaLogoImage, src: logoUrl }),
					React.createElement(Text, { style: styles.ctaTitle }, labels.ctaTitle),
					React.createElement(Text, { style: styles.ctaSubtitle }, labels.ctaSubtitle),
					React.createElement(Text, { style: styles.ctaQuestion }, labels.ctaQuestion),
					React.createElement(Text, { style: styles.ctaButton }, labels.ctaButton),
					React.createElement(Text, { style: { ...styles.ctaSubtitle, marginTop: 8 } }, labels.ctaEmail)
				),
				// Disclaimer
				React.createElement(Text, { style: styles.disclaimer }, labels.disclaimer),
				// Footer
				React.createElement(Text, { style: styles.footer }, labels.footer)
			)
		);

	// Generate and download PDF
	const blob = await pdf(React.createElement(QuoteDocument)).toBlob();
	const url = URL.createObjectURL(blob);
	const link = document.createElement('a');
	link.href = url;
	link.download = `cotizacion-ac-${new Date().toISOString().split('T')[0]}.pdf`;
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
	URL.revokeObjectURL(url);
}
